// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.0
// source: github.com/buildbarn/bb-action-router/pkg/proto/configuration/registry_auth/registry_auth.proto

package registry_auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistryAuthenticationConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Authentication:
	//
	//	*RegistryAuthenticationConfiguration_Anonymous
	//	*RegistryAuthenticationConfiguration_Inline
	//	*RegistryAuthenticationConfiguration_CredentialsJsonPath
	Authentication isRegistryAuthenticationConfiguration_Authentication `protobuf_oneof:"authentication"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegistryAuthenticationConfiguration) Reset() {
	*x = RegistryAuthenticationConfiguration{}
	mi := &file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryAuthenticationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryAuthenticationConfiguration) ProtoMessage() {}

func (x *RegistryAuthenticationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryAuthenticationConfiguration.ProtoReflect.Descriptor instead.
func (*RegistryAuthenticationConfiguration) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegistryAuthenticationConfiguration) GetAuthentication() isRegistryAuthenticationConfiguration_Authentication {
	if x != nil {
		return x.Authentication
	}
	return nil
}

func (x *RegistryAuthenticationConfiguration) GetAnonymous() *AnonymousDetails {
	if x != nil {
		if x, ok := x.Authentication.(*RegistryAuthenticationConfiguration_Anonymous); ok {
			return x.Anonymous
		}
	}
	return nil
}

func (x *RegistryAuthenticationConfiguration) GetInline() *AuthenticationDetails {
	if x != nil {
		if x, ok := x.Authentication.(*RegistryAuthenticationConfiguration_Inline); ok {
			return x.Inline
		}
	}
	return nil
}

func (x *RegistryAuthenticationConfiguration) GetCredentialsJsonPath() string {
	if x != nil {
		if x, ok := x.Authentication.(*RegistryAuthenticationConfiguration_CredentialsJsonPath); ok {
			return x.CredentialsJsonPath
		}
	}
	return ""
}

type isRegistryAuthenticationConfiguration_Authentication interface {
	isRegistryAuthenticationConfiguration_Authentication()
}

type RegistryAuthenticationConfiguration_Anonymous struct {
	Anonymous *AnonymousDetails `protobuf:"bytes,1,opt,name=anonymous,proto3,oneof"`
}

type RegistryAuthenticationConfiguration_Inline struct {
	Inline *AuthenticationDetails `protobuf:"bytes,2,opt,name=inline,proto3,oneof"`
}

type RegistryAuthenticationConfiguration_CredentialsJsonPath struct {
	CredentialsJsonPath string `protobuf:"bytes,3,opt,name=credentials_json_path,json=credentialsJsonPath,proto3,oneof"`
}

func (*RegistryAuthenticationConfiguration_Anonymous) isRegistryAuthenticationConfiguration_Authentication() {
}

func (*RegistryAuthenticationConfiguration_Inline) isRegistryAuthenticationConfiguration_Authentication() {
}

func (*RegistryAuthenticationConfiguration_CredentialsJsonPath) isRegistryAuthenticationConfiguration_Authentication() {
}

type AnonymousDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registry      string                 `protobuf:"bytes,1,opt,name=registry,proto3" json:"registry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnonymousDetails) Reset() {
	*x = AnonymousDetails{}
	mi := &file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnonymousDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnonymousDetails) ProtoMessage() {}

func (x *AnonymousDetails) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnonymousDetails.ProtoReflect.Descriptor instead.
func (*AnonymousDetails) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AnonymousDetails) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

type AuthenticationDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registry      string                 `protobuf:"bytes,1,opt,name=registry,proto3" json:"registry,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationDetails) Reset() {
	*x = AuthenticationDetails{}
	mi := &file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationDetails) ProtoMessage() {}

func (x *AuthenticationDetails) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationDetails.ProtoReflect.Descriptor instead.
func (*AuthenticationDetails) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticationDetails) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

func (x *AuthenticationDetails) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticationDetails) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_rawDesc = "" +
	"\n" +
	"_github.com/buildbarn/bb-action-router/pkg/proto/configuration/registry_auth/registry_auth.proto\x12%buildbarn.configuration.registry_auth\"\x9e\x02\n" +
	"#RegistryAuthenticationConfiguration\x12W\n" +
	"\tanonymous\x18\x01 \x01(\v27.buildbarn.configuration.registry_auth.AnonymousDetailsH\x00R\tanonymous\x12V\n" +
	"\x06inline\x18\x02 \x01(\v2<.buildbarn.configuration.registry_auth.AuthenticationDetailsH\x00R\x06inline\x124\n" +
	"\x15credentials_json_path\x18\x03 \x01(\tH\x00R\x13credentialsJsonPathB\x10\n" +
	"\x0eauthentication\".\n" +
	"\x10AnonymousDetails\x12\x1a\n" +
	"\bregistry\x18\x01 \x01(\tR\bregistry\"k\n" +
	"\x15AuthenticationDetails\x12\x1a\n" +
	"\bregistry\x18\x01 \x01(\tR\bregistry\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpasswordBMZKgithub.com/buildbarn/bb-action-router/pkg/proto/configuration/registry_authb\x06proto3"

var (
	file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_rawDesc), len(file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_rawDescData
}

var file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_goTypes = []any{
	(*RegistryAuthenticationConfiguration)(nil), // 0: buildbarn.configuration.registry_auth.RegistryAuthenticationConfiguration
	(*AnonymousDetails)(nil),                    // 1: buildbarn.configuration.registry_auth.AnonymousDetails
	(*AuthenticationDetails)(nil),               // 2: buildbarn.configuration.registry_auth.AuthenticationDetails
}
var file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_depIdxs = []int32{
	1, // 0: buildbarn.configuration.registry_auth.RegistryAuthenticationConfiguration.anonymous:type_name -> buildbarn.configuration.registry_auth.AnonymousDetails
	2, // 1: buildbarn.configuration.registry_auth.RegistryAuthenticationConfiguration.inline:type_name -> buildbarn.configuration.registry_auth.AuthenticationDetails
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() {
	file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_init()
}
func file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_init() {
	if File_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto != nil {
		return
	}
	file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_msgTypes[0].OneofWrappers = []any{
		(*RegistryAuthenticationConfiguration_Anonymous)(nil),
		(*RegistryAuthenticationConfiguration_Inline)(nil),
		(*RegistryAuthenticationConfiguration_CredentialsJsonPath)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_rawDesc), len(file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto = out.File
	file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_goTypes = nil
	file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_registry_auth_registry_auth_proto_depIdxs = nil
}
