load("@rules_go//go:def.bzl", "go_binary", "go_library")
load("@rules_img//img:image.bzl", "image_from_binary")
load("@rules_img//img:load.bzl", "image_load")
load("@rules_img//img:push.bzl", "image_push")

go_library(
    name = "bb_docker_action_router_lib",
    srcs = ["main.go"],
    importpath = "github.com/buildbarn/bb-action-router/cmd/bb_docker_action_router",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/actionrouter",
        "//pkg/docker",
        "//pkg/fetcher",
        "//pkg/proto/configuration/bb_docker_action_router",
        "@bazel_remote_apis//build/bazel/remote/execution/v2:remote_execution_go_proto",
        "@com_github_buildbarn_bb_remote_execution//pkg/proto/remoteactionrouter",
        "@com_github_buildbarn_bb_storage//pkg/auth",
        "@com_github_buildbarn_bb_storage//pkg/blobstore",
        "@com_github_buildbarn_bb_storage//pkg/blobstore/configuration",
        "@com_github_buildbarn_bb_storage//pkg/digest",
        "@com_github_buildbarn_bb_storage//pkg/global",
        "@com_github_buildbarn_bb_storage//pkg/grpc",
        "@com_github_buildbarn_bb_storage//pkg/program",
        "@com_github_buildbarn_bb_storage//pkg/util",
        "@com_github_buildbarn_bb_storage//pkg/zstd",
        "@com_github_prometheus_client_golang//prometheus",
        "@com_github_prometheus_client_golang//prometheus/promauto",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//types/known/anypb",
    ],
)

go_binary(
    name = "bb_docker_action_router",
    embed = [":bb_docker_action_router_lib"],
    pure = "on",
    visibility = ["//visibility:public"],
)

image_from_binary(
    name = "bb_docker_action_router_image",
    binary = ":bb_docker_action_router",
    include_runfiles = False,
    visibility = ["//visibility:public"],
)

image_push(
    name = "push_bb_docker_action_router",
    image = ":bb_docker_action_router_image",
    registry = "docker.io",
    repository = "buildbarn/bb_action_router",
    tag = "latest",
)

# Produces a "docker save" tarball for `kind load image-archive`.
image_load(
    name = "bb_docker_action_router_image_load",
    image = ":bb_docker_action_router_image",
    tag = "bb_docker_action_router:e2e",
)