// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.0
// source: github.com/buildbarn/bb-action-router/pkg/proto/configuration/bb_docker_action_router/bb_docker_action_router.proto

package bb_docker_action_router

import (
	build_user "github.com/buildbarn/bb-action-router/pkg/proto/configuration/build_user"
	registry_auth "github.com/buildbarn/bb-action-router/pkg/proto/configuration/registry_auth"
	blobstore "github.com/buildbarn/bb-storage/pkg/proto/configuration/blobstore"
	global "github.com/buildbarn/bb-storage/pkg/proto/configuration/global"
	grpc "github.com/buildbarn/bb-storage/pkg/proto/configuration/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationConfiguration struct {
	state                      protoimpl.MessageState            `protogen:"open.v1"`
	GrpcServers                []*grpc.ServerConfiguration       `protobuf:"bytes,1,rep,name=grpc_servers,json=grpcServers,proto3" json:"grpc_servers,omitempty"`
	MaximumMessageSizeBytes    int64                             `protobuf:"varint,2,opt,name=maximum_message_size_bytes,json=maximumMessageSizeBytes,proto3" json:"maximum_message_size_bytes,omitempty"`
	Global                     *global.Configuration             `protobuf:"bytes,3,opt,name=global,proto3" json:"global,omitempty"`
	Blobstore                  *blobstore.BlobstoreConfiguration `protobuf:"bytes,4,opt,name=blobstore,proto3" json:"blobstore,omitempty"`
	ContainerImageReplacements map[string]string                 `protobuf:"bytes,5,rep,name=container_image_replacements,json=containerImageReplacements,proto3" json:"container_image_replacements,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BuildUser                  *build_user.BuildUser             `protobuf:"bytes,8,opt,name=build_user,json=buildUser,proto3" json:"build_user,omitempty"`
	// Types that are valid to be assigned to Mode:
	//
	//	*ApplicationConfiguration_Sideloaded
	//	*ApplicationConfiguration_Inline
	Mode          isApplicationConfiguration_Mode `protobuf_oneof:"mode"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationConfiguration) Reset() {
	*x = ApplicationConfiguration{}
	mi := &file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfiguration) ProtoMessage() {}

func (x *ApplicationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfiguration.ProtoReflect.Descriptor instead.
func (*ApplicationConfiguration) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationConfiguration) GetGrpcServers() []*grpc.ServerConfiguration {
	if x != nil {
		return x.GrpcServers
	}
	return nil
}

func (x *ApplicationConfiguration) GetMaximumMessageSizeBytes() int64 {
	if x != nil {
		return x.MaximumMessageSizeBytes
	}
	return 0
}

func (x *ApplicationConfiguration) GetGlobal() *global.Configuration {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *ApplicationConfiguration) GetBlobstore() *blobstore.BlobstoreConfiguration {
	if x != nil {
		return x.Blobstore
	}
	return nil
}

func (x *ApplicationConfiguration) GetContainerImageReplacements() map[string]string {
	if x != nil {
		return x.ContainerImageReplacements
	}
	return nil
}

func (x *ApplicationConfiguration) GetBuildUser() *build_user.BuildUser {
	if x != nil {
		return x.BuildUser
	}
	return nil
}

func (x *ApplicationConfiguration) GetMode() isApplicationConfiguration_Mode {
	if x != nil {
		return x.Mode
	}
	return nil
}

func (x *ApplicationConfiguration) GetSideloaded() *SideloadedMode {
	if x != nil {
		if x, ok := x.Mode.(*ApplicationConfiguration_Sideloaded); ok {
			return x.Sideloaded
		}
	}
	return nil
}

func (x *ApplicationConfiguration) GetInline() *InlineMode {
	if x != nil {
		if x, ok := x.Mode.(*ApplicationConfiguration_Inline); ok {
			return x.Inline
		}
	}
	return nil
}

type isApplicationConfiguration_Mode interface {
	isApplicationConfiguration_Mode()
}

type ApplicationConfiguration_Sideloaded struct {
	Sideloaded *SideloadedMode `protobuf:"bytes,6,opt,name=sideloaded,proto3,oneof"`
}

type ApplicationConfiguration_Inline struct {
	Inline *InlineMode `protobuf:"bytes,7,opt,name=inline,proto3,oneof"`
}

func (*ApplicationConfiguration_Sideloaded) isApplicationConfiguration_Mode() {}

func (*ApplicationConfiguration_Inline) isApplicationConfiguration_Mode() {}

type SideloadedMode struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FetcherSocketPath string                 `protobuf:"bytes,1,opt,name=fetcher_socket_path,json=fetcherSocketPath,proto3" json:"fetcher_socket_path,omitempty"`
	ChrootHelperPath  string                 `protobuf:"bytes,2,opt,name=chroot_helper_path,json=chrootHelperPath,proto3" json:"chroot_helper_path,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SideloadedMode) Reset() {
	*x = SideloadedMode{}
	mi := &file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SideloadedMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SideloadedMode) ProtoMessage() {}

func (x *SideloadedMode) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SideloadedMode.ProtoReflect.Descriptor instead.
func (*SideloadedMode) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_rawDescGZIP(), []int{1}
}

func (x *SideloadedMode) GetFetcherSocketPath() string {
	if x != nil {
		return x.FetcherSocketPath
	}
	return ""
}

func (x *SideloadedMode) GetChrootHelperPath() string {
	if x != nil {
		return x.ChrootHelperPath
	}
	return ""
}

type InlineMode struct {
	state                  protoimpl.MessageState                               `protogen:"open.v1"`
	ChrootHelperPath       string                                               `protobuf:"bytes,1,opt,name=chroot_helper_path,json=chrootHelperPath,proto3" json:"chroot_helper_path,omitempty"`
	MaximumImageSizeBytes  int64                                                `protobuf:"varint,2,opt,name=maximum_image_size_bytes,json=maximumImageSizeBytes,proto3" json:"maximum_image_size_bytes,omitempty"`
	ImagePullTimeout       *durationpb.Duration                                 `protobuf:"bytes,3,opt,name=image_pull_timeout,json=imagePullTimeout,proto3" json:"image_pull_timeout,omitempty"`
	RegistryAuthentication []*registry_auth.RegistryAuthenticationConfiguration `protobuf:"bytes,4,rep,name=registry_authentication,json=registryAuthentication,proto3" json:"registry_authentication,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InlineMode) Reset() {
	*x = InlineMode{}
	mi := &file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InlineMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineMode) ProtoMessage() {}

func (x *InlineMode) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineMode.ProtoReflect.Descriptor instead.
func (*InlineMode) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_rawDescGZIP(), []int{2}
}

func (x *InlineMode) GetChrootHelperPath() string {
	if x != nil {
		return x.ChrootHelperPath
	}
	return ""
}

func (x *InlineMode) GetMaximumImageSizeBytes() int64 {
	if x != nil {
		return x.MaximumImageSizeBytes
	}
	return 0
}

func (x *InlineMode) GetImagePullTimeout() *durationpb.Duration {
	if x != nil {
		return x.ImagePullTimeout
	}
	return nil
}

func (x *InlineMode) GetRegistryAuthentication() []*registry_auth.RegistryAuthenticationConfiguration {
	if x != nil {
		return x.RegistryAuthentication
	}
	return nil
}

var File_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_rawDesc = "" +
	"\n" +
	"sgithub.com/buildbarn/bb-action-router/pkg/proto/configuration/bb_docker_action_router/bb_docker_action_router.proto\x12/buildbarn.configuration.bb_docker_action_router\x1a\x1egoogle/protobuf/duration.proto\x1aQgithub.com/buildbarn/bb-storage/pkg/proto/configuration/blobstore/blobstore.proto\x1aKgithub.com/buildbarn/bb-storage/pkg/proto/configuration/global/global.proto\x1aGgithub.com/buildbarn/bb-storage/pkg/proto/configuration/grpc/grpc.proto\x1aYgithub.com/buildbarn/bb-action-router/pkg/proto/configuration/build_user/build_user.proto\x1a_github.com/buildbarn/bb-action-router/pkg/proto/configuration/registry_auth/registry_auth.proto\"\xda\x06\n" +
	"\x18ApplicationConfiguration\x12T\n" +
	"\fgrpc_servers\x18\x01 \x03(\v21.buildbarn.configuration.grpc.ServerConfigurationR\vgrpcServers\x12;\n" +
	"\x1amaximum_message_size_bytes\x18\x02 \x01(\x03R\x17maximumMessageSizeBytes\x12E\n" +
	"\x06global\x18\x03 \x01(\v2-.buildbarn.configuration.global.ConfigurationR\x06global\x12W\n" +
	"\tblobstore\x18\x04 \x01(\v29.buildbarn.configuration.blobstore.BlobstoreConfigurationR\tblobstore\x12\xab\x01\n" +
	"\x1ccontainer_image_replacements\x18\x05 \x03(\v2i.buildbarn.configuration.bb_docker_action_router.ApplicationConfiguration.ContainerImageReplacementsEntryR\x1acontainerImageReplacements\x12L\n" +
	"\n" +
	"build_user\x18\b \x01(\v2-.buildbarn.configuration.build_user.BuildUserR\tbuildUser\x12a\n" +
	"\n" +
	"sideloaded\x18\x06 \x01(\v2?.buildbarn.configuration.bb_docker_action_router.SideloadedModeH\x00R\n" +
	"sideloaded\x12U\n" +
	"\x06inline\x18\a \x01(\v2;.buildbarn.configuration.bb_docker_action_router.InlineModeH\x00R\x06inline\x1aM\n" +
	"\x1fContainerImageReplacementsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04mode\"n\n" +
	"\x0eSideloadedMode\x12.\n" +
	"\x13fetcher_socket_path\x18\x01 \x01(\tR\x11fetcherSocketPath\x12,\n" +
	"\x12chroot_helper_path\x18\x02 \x01(\tR\x10chrootHelperPath\"\xc2\x02\n" +
	"\n" +
	"InlineMode\x12,\n" +
	"\x12chroot_helper_path\x18\x01 \x01(\tR\x10chrootHelperPath\x127\n" +
	"\x18maximum_image_size_bytes\x18\x02 \x01(\x03R\x15maximumImageSizeBytes\x12G\n" +
	"\x12image_pull_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x10imagePullTimeout\x12\x83\x01\n" +
	"\x17registry_authentication\x18\x04 \x03(\v2J.buildbarn.configuration.registry_auth.RegistryAuthenticationConfigurationR\x16registryAuthenticationBWZUgithub.com/buildbarn/bb-action-router/pkg/proto/configuration/bb_docker_action_routerb\x06proto3"

var (
	file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_rawDesc), len(file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_rawDescData
}

var file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_goTypes = []any{
	(*ApplicationConfiguration)(nil),         // 0: buildbarn.configuration.bb_docker_action_router.ApplicationConfiguration
	(*SideloadedMode)(nil),                   // 1: buildbarn.configuration.bb_docker_action_router.SideloadedMode
	(*InlineMode)(nil),                       // 2: buildbarn.configuration.bb_docker_action_router.InlineMode
	nil,                                      // 3: buildbarn.configuration.bb_docker_action_router.ApplicationConfiguration.ContainerImageReplacementsEntry
	(*grpc.ServerConfiguration)(nil),         // 4: buildbarn.configuration.grpc.ServerConfiguration
	(*global.Configuration)(nil),             // 5: buildbarn.configuration.global.Configuration
	(*blobstore.BlobstoreConfiguration)(nil), // 6: buildbarn.configuration.blobstore.BlobstoreConfiguration
	(*build_user.BuildUser)(nil),             // 7: buildbarn.configuration.build_user.BuildUser
	(*durationpb.Duration)(nil),              // 8: google.protobuf.Duration
	(*registry_auth.RegistryAuthenticationConfiguration)(nil), // 9: buildbarn.configuration.registry_auth.RegistryAuthenticationConfiguration
}
var file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_depIdxs = []int32{
	4, // 0: buildbarn.configuration.bb_docker_action_router.ApplicationConfiguration.grpc_servers:type_name -> buildbarn.configuration.grpc.ServerConfiguration
	5, // 1: buildbarn.configuration.bb_docker_action_router.ApplicationConfiguration.global:type_name -> buildbarn.configuration.global.Configuration
	6, // 2: buildbarn.configuration.bb_docker_action_router.ApplicationConfiguration.blobstore:type_name -> buildbarn.configuration.blobstore.BlobstoreConfiguration
	3, // 3: buildbarn.configuration.bb_docker_action_router.ApplicationConfiguration.container_image_replacements:type_name -> buildbarn.configuration.bb_docker_action_router.ApplicationConfiguration.ContainerImageReplacementsEntry
	7, // 4: buildbarn.configuration.bb_docker_action_router.ApplicationConfiguration.build_user:type_name -> buildbarn.configuration.build_user.BuildUser
	1, // 5: buildbarn.configuration.bb_docker_action_router.ApplicationConfiguration.sideloaded:type_name -> buildbarn.configuration.bb_docker_action_router.SideloadedMode
	2, // 6: buildbarn.configuration.bb_docker_action_router.ApplicationConfiguration.inline:type_name -> buildbarn.configuration.bb_docker_action_router.InlineMode
	8, // 7: buildbarn.configuration.bb_docker_action_router.InlineMode.image_pull_timeout:type_name -> google.protobuf.Duration
	9, // 8: buildbarn.configuration.bb_docker_action_router.InlineMode.registry_authentication:type_name -> buildbarn.configuration.registry_auth.RegistryAuthenticationConfiguration
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() {
	file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_init()
}
func file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_init() {
	if File_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto != nil {
		return
	}
	file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_msgTypes[0].OneofWrappers = []any{
		(*ApplicationConfiguration_Sideloaded)(nil),
		(*ApplicationConfiguration_Inline)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_rawDesc), len(file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto = out.File
	file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_goTypes = nil
	file_github_com_buildbarn_bb_action_router_pkg_proto_configuration_bb_docker_action_router_bb_docker_action_router_proto_depIdxs = nil
}
