load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@rules_go//go:def.bzl", "go_library")
load("@rules_go//proto:def.bzl", "go_proto_library")

proto_library(
    name = "bb_docker_action_router_proto",
    srcs = ["bb_docker_action_router.proto"],
    import_prefix = "github.com/buildbarn/bb-action-router",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/proto/configuration/build_user:build_user_proto",
        "//pkg/proto/configuration/registry_auth:registry_auth_proto",
        "@com_github_buildbarn_bb_storage//pkg/proto/configuration/blobstore:blobstore_proto",
        "@com_github_buildbarn_bb_storage//pkg/proto/configuration/global:global_proto",
        "@com_github_buildbarn_bb_storage//pkg/proto/configuration/grpc:grpc_proto",
        "@protobuf//:duration_proto",
    ],
)

go_proto_library(
    name = "bb_docker_action_router_go_proto",
    importpath = "github.com/buildbarn/bb-action-router/pkg/proto/configuration/bb_docker_action_router",
    proto = ":bb_docker_action_router_proto",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/proto/configuration/build_user",
        "//pkg/proto/configuration/registry_auth",
        "@com_github_buildbarn_bb_storage//pkg/proto/configuration/blobstore",
        "@com_github_buildbarn_bb_storage//pkg/proto/configuration/global",
        "@com_github_buildbarn_bb_storage//pkg/proto/configuration/grpc",
    ],
)

go_library(
    name = "bb_docker_action_router",
    embed = [":bb_docker_action_router_go_proto"],
    importpath = "github.com/buildbarn/bb-action-router/pkg/proto/configuration/bb_docker_action_router",
    visibility = ["//visibility:public"],
)
