apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bb-e2e

resources:
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: bb-router-config
    files:
      - router.jsonnet=action-router.jsonnet
      - fetcher.jsonnet=root-fetcher.jsonnet
  - name: bb-chroot-helper-config
    files:
      - config.toml=chroot-helper.toml

patches:
  - path: executor-patch.yaml
    target:
      kind: Deployment
      name: executor
