load("@bazel_lib//lib:transitions.bzl", "platform_transition_binary")
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")
load("@rules_img//img:image.bzl", "image_manifest")
load("@rules_img//img:layer.bzl", "image_layer")
load("@rules_img//img:load.bzl", "image_load")

cc_library(
    name = "bb_chroot_helper_lib",
    srcs = [
        "main.cc",
        "mount.cc",
        "mount.h",
    ],
    copts = ["-std=c++17"],
    target_compatible_with = ["@platforms//os:linux"],
)

cc_binary(
    name = "bb_chroot_helper",
    copts = ["-std=c++17"],
    # Produce a fully static binary as we run distroless.
    features = [
        "fully_static_link",
    ],
    target_compatible_with = ["@platforms//os:linux"],
    visibility = ["//visibility:public"],
    deps = [":bb_chroot_helper_lib"],
)

# Useful when cross-compiling from other platforms.
platform_transition_binary(
    name = "bb_chroot_helper_linux_musl",
    binary = ":bb_chroot_helper",
    target_platform = "//build/platforms:linux_x86_64_musl",
)

# Integration test: Go binary that acts as both test driver, action command and
# mock server. It is intended to run from within the container image below.
go_library(
    name = "integration_test_lib",
    srcs = ["integration_test.go"],
    importpath = "github.com/buildbarn/bb-action-router/cmd/bb_chroot_helper",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "integration_test",
    embed = [":integration_test_lib"],
    pure = "on",
    visibility = ["//visibility:public"],
)

image_layer(
    name = "integration_test_layer",
    srcs = {
        "/bin/bb_chroot_helper": ":bb_chroot_helper",
        "/bin/bb_integration_test": ":integration_test",
    },
    include_runfiles = False,
)

# This contains integration tests, currently needs to be invoked manually.
image_manifest(
    name = "integration_test_image",
    entrypoint = ["/bin/bb_integration_test"],
    layers = [":integration_test_layer"],
    target_compatible_with = ["@platforms//os:linux"],
    visibility = ["//visibility:public"],
)

image_load(
    name = "integration_test_image_load",
    image = ":integration_test_image",
    tag = "bb_chroot_helper_integration_test:latest",
    target_compatible_with = ["@platforms//os:linux"],
)

go_test(
    name = "bb_chroot_helper_test",
    srcs = ["integration_test.go"],
)
